@echo off
set ANTHROPIC_BASE_URL=http://localhost:20128/v1
set ANTHROPIC_AUTH_TOKEN=sk-fa4a3f17cda3ee5e-2874m9-77d142dc
set ANTHROPIC_API_KEY=
set ANTHROPIC_MODEL=my-combo
set ANTHROPIC_SMALL_FAST_MODEL=my-combo
set CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
claude %*